### ISSUE TITLE
Mix-Up

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-ietf-oauth-security-topics#1]
Review feedback from Hans.

About the description of the mixup attack: as long as the attacker is able to trigger a request (by having the user click a link) and read the query/POST parameters on the A-AS (perhaps from the logs) he can execute a mixup attack by starting from the A-AS rather than the H-AS (as demonstrated in the OAuth 2.0 security workshop in Darmstadt December 2016). Perhaps this can be made more explicit.

**Comment by danielfett** [comment]
Made this more explicit.
