### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-ietf-oauth-security-topics#2]
Review feedback from Hans:

Overall:
- grammar in the first sections: there's a lot of comma-separated sentences that could/should be reworked by a native speaker
-	perhaps readers guidance pointing developers straight to section 3. as Torsten said on the call would be useful
-	as also discussed on the call, perhaps it would be good to spell out how this BCP relates to the original OAuth 2.0 security considerations in the RFC(s)

**Comment by tlodderstedt** [comment]
P3 1. Introduction
Usage of OAuth vs. OAuth 2.0 across the document: perhaps explain that in the remainder OAuth refers to OAuth 2.0.

First bullet:
-	CSRF and referrer header are being mentioned without explaining the abbreviation, context or reference. And btw, it is the “referer” header…
-	“defense in depth” -> “in depth defense” ?
Third bullet:
-	I believe those higher security use cases were considered from the start, but they were not acted upon before (e.g. MAC spec was left abandoned).

P4 first paragraph, in the middle:
“This way the same..” -> “In this way the same…”
“serves as a frontend…” -> “serve as a frontend…”
“in a multi-tenancy.” -> “in multi-tenant environment.”

In general there are a lot of sentences broken up by comma’s that could be rearranged and do without the comma’s.

1.1 the whole section is comprised of comma-split sentences that could be re-arranged..

**Comment by danielfett** [comment]
I tried to fix all these things when doing editorial changes over the last days.
