### ISSUE TITLE
private_key_jwt or RFC7523

### ISSUE THREAD

**Issue by ioggstream** [oauthstuff/draft-ietf-oauth-security-topics#23]
## Question

this spec mentions private_key_jwt which iiuc is not defined in an RFC.
Shouldn't we mention RFC 7523?

**Comment by tlodderstedt** [comment]
The spec references the OIDC Core Spec that defines this method. Why isn't that appropriate?

**Comment by peppelinux** [comment]
@ioggstream at the time private_key_jwt was included in the oidc core rfc7523 did not yet exist, it was just a draft.
in any case the links in the section "19.1. Normative References" correctly points to current RFCs

**Comment by danielfett** [comment]
I think there is nothing to do here - closing.

**Comment by aaronpk** [comment]
I was dealing with this with OAuth 2.1 as well and updated the reference to the IETF RFC since the OIDC spec basically just references it too. I'd suggest referencing RFC7523 as well
