### ISSUE TITLE
Provide rationale for PKCE rules

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-ietf-oauth-security-topics#27]
Explain what we explained in the informal OAuth WG session at IETF 113.

**Comment by danielfett** [comment]
Also: "Clients MUST prevent **misuse of authorization codes and** injection (replay) of authorization codes into the authorization response …"

**Comment by selfissued** [comment]
The rationale for this text at https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#name-authorization-code-grant "Public clients MUST use PKCE [[RFC7636](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#RFC7636)] to this end. For confidential clients, the use of PKCE [[RFC7636](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#RFC7636)] is RECOMMENDED." is not at all obvious, as discussed in Vienna.

At a minimum, the spec needs to say why the use of `nonce` is insufficient for public clients, versus it being sufficient for confidential clients.  (The slides presented in the side meetings in Vienna may contain these answers.)

Knowing *why* will help developers to be informed about the threats and help them make rational choices.

**Comment by danielfett** [comment]
This has been covered in https://github.com/oauthstuff/draft-ietf-oauth-security-topics/pull/28
