### ISSUE TITLE
Unconditional AS support for PKCE is overkill

### ISSUE THREAD

**Issue by selfissued** [oauthstuff/draft-ietf-oauth-security-topics#30]
https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#name-authorization-code-grant says: "Authorization servers MUST support PKCE [[RFC7636](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#RFC7636)]".  Yet PKCE is unnecessary, even from a security point of view, when the AS is only used for OpenID Connect - which supports the `nonce`, and it's particularly unnecessary for Confidential Clients.

Please change this unconditional statement to instead say:
"Authorization servers used for non-OpenID Connect clients MUST support PKCE [RFC7636]."

Or at least, to say:
"Authorization servers used for non-OpenID Connect clients or public clients MUST support PKCE [RFC7636]."

**Comment by brockallen** [comment]
If the AS implements/requires PKCE, then hybrid flow/nonce is no longer necessary, right? There is something nice to only needing a single flow (code+PKCE) for both OIDC and OAuth interactive workflows (consistency, less for people to learn/remember, simpler implementations).

**Comment by danielfett** [comment]
PKCE provides a robust defense against CSRF as discussed at IETF113 and now also described in the text: https://github.com/oauthstuff/draft-ietf-oauth-security-topics/blob/master/attacks-and-mitigations.md#countermeasures-csrf_countermeasures

Neither nonce nor state provide the same level of protection. Additionally, state is often not used correctly, so a robust alternative is required.

**Comment by danielfett** [comment]
We agreed at IETF114 to say something like: "If the client sends a PKCE parameter in the authorization request, the server must enforce it in the token endpoint."
