### ISSUE TITLE
Overreaching statement about access tokens in the implicit flow

### ISSUE THREAD

**Issue by selfissued** [oauthstuff/draft-ietf-oauth-security-topics#31]
https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#name-implicit-grant says "no viable mechanism exists to cryptographically bind access tokens issued in the authorization response to a certain client as it is recommended in [Section 2.2](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#token_replay_prevention). This makes replay detection for such access tokens at resource servers impossible."

This is not true when OpenID Connect is used.  The `at_hash` claim in the ID Token together with the `aud` claim accomplish exactly that.

At a minimum, please amend the first sentence to say "no viable mechanism exists to cryptographically bind access tokens issued in the authorization response to a certain client *unless OpenID Connect is used*".  Or if you want to be more comprehensive, also explain how  `at_hash`  and `aud` accomplish this.

**Comment by danielfett** [comment]
Please correct me if I'm wrong, but even with `at_hash` and `aud`, the access token is not bound to the client. Anybody that gets hold of the AT can use it immediately. Unlike with DPoP and MTLS, where one would need a private key to use the AT.

**Comment by aaronpk** [comment]
That is my understanding as well. The reason it's not possible in the implicit flow is because there is no way for the client to provide a proof of possession mechanism when the token is delivered, in contrast to the authorization code flow where the client can provide a PoP proof in the POST request. Perhaps this reasoning could be clarified to support this statement.

**Comment by danielfett** [comment]
We discussed at IETF 114 side-side meeting to change the paragraph to roughly something like this:

> Moreover, no viable mechanism exists to cryptographically bind access tokens to a specific client ( as it is recommended in [Section 2.2](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#token_replay_prevention)) when they are issued in the authorization response. This means that leaked or stolen access tokens can be used at resource servers.

**Comment by danielfett** [comment]
We discussed at IETF 114 side-side meeting to change the paragraph to roughly something like this:

> Moreover, no viable mechanism exists to cryptographically bind access tokens to a specific client ( as it is recommended in [Section 2.2](https://tools.ietf.org/id/draft-ietf-oauth-security-topics-19.html#token_replay_prevention)) when they are issued in the authorization response. This means that leaked or stolen access tokens can be used at resource servers.
