### ISSUE TITLE
Client impersonating resource owner

### ISSUE THREAD

**Issue by aaronpk** [oauthstuff/draft-ietf-oauth-security-topics#70]
In [Section 4.14.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.14.1) it currently says:

> Authorization servers SHOULD NOT allow clients to influence their client_id or any other Claim if that can cause confusion with a genuine resource owner. Where this cannot be avoided, authorization servers MUST provide other means for the resource server to distinguish between access tokens authorized by a resource owner from access tokens authorized by the client itself.

At the last IETF meeting, we agreed to change the description of a client ID in OAuth 2.1 to include this: 

> While the Authorization Server typically issues the client identifier itself, it may also serve clients whose client identifier was created by a party other than the Authorization Server.

I think we should flip the language around on the Security BCP section to make it more clear when the "SHOULD NOT" applies. So something like: 

> If the authorization server has a common namespace for client IDs and user identifiers, causing the resource server to be unable to distinguish an access token authorized by a resource owner from an access token authorized by a client itself, the authorization server SHOULD NOT allow clients to influence their `client_id` or any other claim that could cause confusion with a genuine resource owner. Where this cannot be avoided, authorization servers MUST provide other means for the resource server to distinguish between the two types of access tokens.

**Comment by danielfett** [comment]
See PR #75. I changed "any other claims" to "any claims" since the client ID is not (only) a claim.

**Comment by danielfett** [comment]
Merged.
