### ISSUE TITLE
Redirect URI matching is not defined well

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-ietf-oauth-security-topics#71]
We currently say:

> This means the authorization server MUST compare the two URIs using simple string comparison as defined in [[RFC3986](https://www.rfc-editor.org/info/rfc3986)], Section 6.2.1.

But 3986 does not actually contain a good description of the matching. We need to improve that.

**Comment by CheariX** [comment]
I just looked into [Section 6.2.1](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.1). It says:

> If two URIs, when considered as character strings, are identical, then it is safe to conclude that they are equivalent.

For me, this is very clear. What are you referring to?
Do you want to laxify the comparison?
