### ISSUE TITLE
Wrong Client Domain in Example (4.1.2 Redirect URI Validation Attacks on Implicit Grant)

### ISSUE THREAD

**Issue by kmzs** [oauthstuff/draft-ietf-oauth-security-topics#73]
A minor mistake in [4.1.2 Redirect URI Validation Attacks on Implicit Grant](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-21.html#name-redirect-uri-validation-atta):

Throughout the example the client's domain is `client.somesite.example`. In Line 153 `example.com` is used instead:
https://github.com/oauthstuff/draft-ietf-oauth-security-topics/blob/70562d72adaa189b083b106fb9c194364be8f7b0/attacks-and-mitigations.md?plain=1#L153

**Comment by danielfett** [comment]
Merged.
